/**
 * @description computes the nth Fibonacci number using a recursive approach, where
 * the function calls itself with decreasing argument values until it reaches the
 * base case of num <= 1, at which point it returns the value directly.
 * 
 * @param { integer } num - 0-based index of the Fibonacci number to be generated by
 * the function.
 * 
 * @returns { integer } the nth Fibonacci number for a given input `num`.
 */
function fibonacci(num) {
    if (num <= 1) return num;
    return fibonacci(num - 1) + fibonacci(num - 2);
}

/**
 * @description determines whether a given number is prime or not by performing various
 * checks, including checking for divisibility by 2 and 3, and using a trial division
 * method to check for composite numbers.
 * 
 * @param { integer } num - 2-digit integer to be tested for primality.
 * 
 * @returns { boolean } a boolean value indicating whether the input number is prime
 * or not.
 */
function isPrime(num) {
    if (num <= 1) return false;
    if (num <= 3) return true;
    if (num % 2 === 0 || num % 3 === 0) return false;
    let i = 5;
    while (i * i <= num) {
        if (num % i === 0 || num % (i + 2) === 0) return false;
        i += 6;
    }
    return true;
}

/**
 * @description computes the factorial of a given integer `num`. It recursively calls
 * itself with `num - 1` as input until it reaches 0, at which point it returns 1.
 * 
 * @param { integer } num - for which the factorial is calculated, and its value
 * determines the result returned by the function.
 * 
 * @returns { integer } the value of the factorial of a given integer.
 */
function factorial(num) {
    if (num === 0) return 1;
    return num * factorial(num - 1);
}

/**
 * @description takes a string as input and reverses its characters, then joins them
 * back into a string using the original delimiter.
 * 
 * @param { string } str - string to be reversed.
 * 
 * @returns { string } a string that represents the original input string with its
 * characters arranged in reverse order.
 */
function reverseString(str) {
    return str.split("").reverse().join("");
}

/**
 * @description combines two arrays by concatenating them into a single array using
 * the spread operator ...
 * 
 * @param { array } arr1 - 1st array to be merged with the second array.
 * 
 * @param { array } arr2 - 2nd array to be merged with the elements of `arr1`.
 * 
 * @returns { array } a new array that contains all the elements of both input arrays
 * concatenated together.
 */
function mergeArrays(arr1, arr2) {
    return [...arr1, ...arr2];
}

/**
 * @description iterates through an array, comparing adjacent elements and swapping
 * them if they are out of order based on a comparison operator.
 * 
 * @param { array } arr - 1D array that is being sorted by the bubble sort algorithm
 * implemented in the function.
 * 
 * @returns { array } a sorted array of numbers.
 */
function bubbleSort(arr) {
    const len = arr.length;
    for (let i = 0; i < len; i++) {
        for (let j = 0; j < len - i - 1; j++) {
            if (arr[j] > arr[j + 1]) {
                const temp = arr[j];
                arr[j] = arr[j + 1];
                arr[j + 1] = temp;
            }
        }
    }
    return arr;
}

class Animal {
    /**
     * @description initializes an object with the given `name` and `species`.
     * 
     * @param { string } name - name of the creature.
     * 
     * @param { string } species - animal species of the object being constructed, and
     * is used to determine the characteristics and behavior of the object in the code.
     */
    constructor(name, species) {
        this.name = name;
        this.species = species;
    }
    /**
     * @description logs the message "Animal sound" to the console.
     */
    makeSound() {
        console.log("Animal sound");
    }
}

const myAnimal = new Animal("Leo", "Lion");

console.log(fibonacci(10));
console.log(isPrime(17));
console.log(factorial(5));
console.log(reverseString("hello"));
console.log(mergeArrays([1, 2, 3], [4, 5, 6]));
console.log(bubbleSort([5, 3, 8, 1, 2]));
console.log(myAnimal);
myAnimal.makeSound();
