/**
 * @description calculates the nth Fibonacci number by recursively calling itself
 * with arguments num - 1 and num - 2, and returning their sum.
 * 
 * @param { integer } num - 0-based index of the Fibonacci number to be generated by
 * the function.
 * 
 * @returns { integer } the nth Fibonacci number, calculated recursively.
 */
function fibonacci(num) {
    if (num <= 1) return num;
    return fibonacci(num - 1) + fibonacci(num - 2);
}

/**
 * @description checks if a given number is prime by iteratively testing whether it
 * has any factors other than itself and 3, using a modified Sieve of Eratosthenes algorithm.
 * 
 * @param { number } num - 9-digit number that is being checked for primality.
 * 
 * @returns { boolean } a boolean value indicating whether the input number is prime
 * or not.
 */
function isPrime(num) {
    if (num <= 1) return false;
    if (num <= 3) return true;
    if (num % 2 === 0 || num % 3 === 0) return false;
    let i = 5;
    while (i * i <= num) {
        if (num % i === 0 || num % (i + 2) === 0) return false;
        i += 6;
    }
    return true;
}

/**
 * @description calculates the value of a given number's factorial, recursively calling
 * itself until reaching 0 as input.
 * 
 * @param { integer } num - 3-dimensional index of the recursive call.
 * 
 * @returns { integer } the value of `num!`, calculated recursively.
 */
function factorial(num) {
    if (num === 0) return 1;
    return num * factorial(num - 1);
}

/**
 * @description reverses a given string by splitting it into individual characters,
 * reversing their order, and reconstructing the original string.
 * 
 * @param { string } str - string to be reversed.
 * 
 * @returns { string } the original string reversed.
 */
function reverseString(str) {
    return str.split("").reverse().join("");
}

/**
 * @description combines two arrays into a single array by concatenating its elements
 * in order.
 * 
 * @param { array } arr1 - 1st array to be merged with the second array.
 * 
 * @param { array } arr2 - 2nd array to be merged with the first array in the function.
 * 
 * @returns { array } a concatenation of both input arrays.
 */
function mergeArrays(arr1, arr2) {
    return [...arr1, ...arr2];
}

/**
 * @description iterates through an array, comparing adjacent elements and swapping
 * them if they are out of order based on a greater-than comparison.
 * 
 * @param { array } arr - 2D array to be sorted by the bubble sort algorithm.
 * 
 * @returns { array } a sorted array of values.
 */
function bubbleSort(arr) {
    const len = arr.length;
    for (let i = 0; i < len; i++) {
        for (let j = 0; j < len - i - 1; j++) {
            if (arr[j] > arr[j + 1]) {
                const temp = arr[j];
                arr[j] = arr[j + 1];
                arr[j + 1] = temp;
            }
        }
    }
    return arr;
}

class Animal {
    /**
     * @description establishes an object's properties. It assigns `name` and `species`
     * values to the newly created object instance.
     * 
     * @param { string } name - name of the creature.
     * 
     * @param { string } species - animal's species in the constructor function of the
     * Animal class.
     */
    constructor(name, species) {
        this.name = name;
        this.species = species;
    }
    /**
     * @description logs an "Animal sound" message to the console.
     */
    makeSound() {
        console.log("Animal sound");
    }
}

const myAnimal = new Animal("Leo", "Lion");

console.log(fibonacci(10));
console.log(isPrime(17));
console.log(factorial(5));
console.log(reverseString("hello"));
console.log(mergeArrays([1, 2, 3], [4, 5, 6]));
console.log(bubbleSort([5, 3, 8, 1, 2]));
console.log(myAnimal);
myAnimal.makeSound();
